---
title: "Selecting on a Collider"
author: "Andy Grogan-Kaylor"
date: "today"
format:
  html:
    toc: true
    number-sections: true
    code-fold: true
    code-summary: "Show the code"
    theme:
      light: yeti
      dark: vapor
---

# Introduction

Selecting on a *collider* may introduce bias.

# Call Libraries

```{r}
#| output: false

library(ggplot2) # graphics

library(patchwork) # graphics

library(dplyr) # data wrangling

library(sjPlot) # nice tables

set.seed(1234) # set random seed

```

# Simulated Data

```{r}

N <- 1000 # sample size

x <- rnorm(N, 100, 10) # randomly distributed x

e <- rnorm(N, 0, 5) # normal error

y <- 1 * x + e # y is a function of x + random error (e)

z <- x + y # z is a collider

df <- data.frame(x, y, z) # data frame

head(df) # replay

```

```{r}

df$selected <- z > 215

df_selected <- df %>% # data selected on collider
  filter(selected)  # selection criterion

```

# Graphs

```{r}

p1 <- ggplot(df,
             aes(x = x,
                 y = y)) + 
  geom_point(aes(color = selected)) +
  geom_smooth(method = "lm") +
  labs(title = "y ~ x",
       subtitle = "Entire Sample") +
  scale_color_manual(values = c('TRUE' = 'blue', 
                                'FALSE' = 'red')) +
  ylim(50, 150) + # specify y scale
  theme_minimal()

```

```{r}

p2 <- ggplot(df_selected,
             aes(x = x,
                 y = y)) + 
  geom_point(aes(color = selected)) +
  geom_smooth(method = "lm") +
  labs(title = "y ~ x",
       subtitle = "Selected On Collider") +
  scale_color_manual(values = c('TRUE' = 'blue', 
                                'FALSE' = 'red')) +
  ylim(50, 150) + # specify y scale
  theme_minimal()

```

```{r}
#| message: false

p1 + p2

```

# Regressions

```{r}

fit1 <- lm(y ~ x, data = df)

fit2 <- lm(y ~ x, data = df_selected)

tab_model(fit1, fit2,
          dv.labels = c("Entire Sample", "Selected on Collider"))

```



