---
title: "Logarithms"
author: "Andy Grogan-Kaylor"
date: "today"
format:
  revealjs:
    transition: convex
    controls: true
    auto-animate-duration: 2
    incremental: true
    lightbox: true
---

## Linear Functions 

```{r}

x0 <- seq(1,10)

y0 = 2 * x0

plot(x0, 
     y0,
     xlab = "x", 
     ylab = "y", 
     pch = 19, 
     col = "darkorange", 
     main = expression(2 * x == y),
     cex = 2.0, cex.lab = 2.0, cex.main = 2.0,
     ylim = c(0,25))

text(x0, y0 + 3, labels = y0)

```

## Exponential and Logarithmic Functions

:::: {.columns}

::: {.column width="45%"}
$$\color{purple}{y} = \color{red}{b}^\color{blue}{x}$$
```{r}

x1 <- seq(1,10)

y1 = 2^x1

plot(x1, 
     y1,
     xlab = "x", 
     ylab = "y", 
     pch = 19, 
     col = "purple", 
     main = expression(2^x == y),
     cex = 2.0, cex.lab = 2.0, cex.main = 2.0)

text(x1, y1 + 100, labels = y1)

```
:::

::: {.column width="5%"}
$$\iff$$
:::

::: {.column width="45%"}
$$\color{blue}{x} = \log_\color{red}{b}(\color{purple}{y})$$
```{r}

x2 <- seq(1,10)

y2 = log2(x2)

plot(x2, 
     y2,
     xlab = "y", 
     ylab = "x", 
     pch = 19, 
     col = "blue", 
     main = expression(x == log[2](y)),
     cex = 2.0, cex.lab = 2.0, cex.main = 2.0)

text(x2, y2 - .5, labels = round(y2, 2))

```
:::

::::

::: {.callout-tip collapse="true"}
### Key Idea

The exponential and logarithmic functions are *inverses* of each other.
:::



## Exponential and Logarithmic Functions Are Mirror Images

```{r}

library(ggplot2)

x3 <- seq(-10,5, by = .01)

x4 <- seq(.01, 10, by = .01)

y3exp <- 2^x3

y4log <- log2(x4)

ggplot(data=NULL) + 
geom_point(aes(x = x3, y = y3exp, color = "exponential")) + 
geom_point(aes(x = x4, y = y4log, color = "logarithmic")) +
labs(title = "Exponential and Logarithmic Functions Are Mirror Images",
x = "x", y = "y") +
scale_color_manual(values = c("purple", "blue")) +
theme_minimal()

ggsave("exponential-logarithmic.png")

```

## Applications of Exponential and Logarithmic Functions

* Categorical Data Analysis 
* Radioactive decay
* Disease spread
* Population growth






