---
title: "Causality Vignettes"
author: "Andy Grogan-Kaylor"
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    highlight: haddock
    toc: true
    toc_float: true
---

# Questions

1. Causal (risk) story A -> B
2. Do you believe it?
3. Do you need more information?
4. How to message it?

# Foster Care

A recently conducted study examined the welfare of foster children who turned 18 and “aged out” of the foster care system into independent living.  This study found a number of disturbing outcomes.  For example, former foster youth are less likely than the average person of their age to have successful labor market experiences, and when former foster youth do obtain jobs, their earnings are very low.  Further, former foster youth are very likely to experience an episode of homelessness within the first year after their discharge from the child welfare system.  Former foster children are also likely to be the victims of sexual or physical aggression.  A state administrator reads about this study in the paper and decides that it indicates that the foster care system is a failure because it fails to adequately prepare children for independent living.  He writes an impassioned editorial in which he cites the study as simply one more piece of evidence that the child welfare system is a shambles.  Is there evidence to support the administrator’s contention?

# Individual Client

You have a client who has problems with anxiety. You have seen them for almost 8 weeks and at each session, they have reported consistent difficulty with anxious feelings.  Your supervisor recommends that you involve your client in a cognitive behavioral intervention to reduce their anxiety levels. The intervention takes several weeks to complete, and after completing the intervention you monitor your client for anxious feelings.  Over the next eight weeks following the intervention you find that your client's anxious feelings are greatly reduced.

# Parents' Speech and Children's Speech

Recent research has attempted to determine whether or not there is a relationship between the richness and complexity with which parents speak to their children and the rate at which children develop a vocabulary.  The research followed children from birth to the age of three years old.  The researchers visited the children every two months and recorded the number and complexity of words used by the parents as well as the number of words used by the children.  One result of the research is that larger parental vocabularies appear to be associated with greater growth in children's vocabularies.  Based on this research, some child advocates recommend that parents be encouraged to talk as much as possible to their children.

# People With Chronic Mental Health Issues

A recent program was designed to increase the success of people with schizophrenia living in the community.  The intent of the program is to prevent negative outcomes such as homelessness, and admission to a psychiatric hospital.  The new program is based on regular visits from a social worker who helps people with schizophrenia to build connections with the communities in which they live.  The social worker assists people with schizophrenia in activities such as applying for and interviewing for jobs, renting apartments, and maintaining compliance with prescribed medication.  Your agency has looked at the program and found that, over the course of a year, people in the program have many fewer hospital admissions than people with schizophrenia who are not in the program.  Based on this finding, do you think that there is evidence that the program is successful?




