---
title: "Data Explorer"
author: "Andy Grogan-Kaylor"
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: true
    highlight: haddock
    number_sections: no
  distill::distill_article:
    highlight: haddock
    toc: yes
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

```

```{css}

h1, h2, h3 {
  font-family: 'Helvetica', 'Arial', sans-serif;
  font-weight: normal;
}
body { 
  font-family: 'Helvetica', 'Arial', sans-serif;
}
.author, .date {
  font-family: 'Helvetica', 'Arial', sans-serif;
  font-weight: normal;
}
.list-group-item.active, 
.list-group-item.active:focus, 
.list-group-item.active:hover {
    z-index: 2;
    color: #FFCB05;
    background-color: #00274C;
    border-color: blue;
}
.nav-pills > li.active > a, .nav-pills > li.active > a:focus {
    color: #FFCB05;
    background-color: #00274C;
}
.nav-pills > li.active > a:hover {
    color: #FFCB05;
    background-color: #00274C;
}
blockquote {
  background: #FFFFFF;
  color: #000;
  border-left: 5px solid #FFCB05;
  margin: 1.5em 10px;
  padding: 0.5em 10px;
}
.caption { 
  display: block;
  color: #00274C;
  font-weight: bold;
}
```


```{r}

load("social-service-agency.RData")

```

# Clients {.tabset .tabset-fade .tabset-pills}

## Pivot Table

Drag and drop other variables into the pivot table--and change the options in the dialog boxes--to explore other views of the data.

```{r}

library(rpivotTable)

rpivotTable::rpivotTable(clients,
                         rendererName = "Bar Chart",
                         aggregatorName = "Median",
                         vals = "mental_health_T2",
                         rows = c("program"))

```

## Map

```{r}

library(leaflet)

m <- leaflet(data = clients, 
             height = 500, 
             width = 1000)  %>% 
  setView(lng = mean(clients$longitude), 
          lat = mean(clients$latitude), 
          zoom = 10) %>% 
  addProviderTiles("Stamen.TonerLite", group = "Toner Lite")

m %>% addCircleMarkers(lng = ~longitude, 
                       lat = ~latitude,
                       popup = ~paste("client:  ", ID),
                       clusterOptions = markerClusterOptions())


```

