---
title: "Notes on Effect Sizes"
author: "Andy Grogan-Kaylor"
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: yes
    toc_float: yes
    number_sections: yes
    highlight: haddock
    css: UM.css
  distill::distill_article:
    highlight: haddock
    toc: yes
  pdf_document: 
    toc: yes
    number_sections: yes
    latex_engine: xelatex
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

# Effect Size Based on Standardized Variable ($ES_z$)

A z score is the deviation of x from its mean in standard deviation units.

$$z = \frac{x_0 - \bar{x}}{sd_x}$$

Our effect sizes could plausibly be thought of as being stated in the $z$ metric. Since we use a standardized dependent variable, our effect size (which I am going to call $ES_z$, for *effect size based upon a z statistic*,) is essentially:

$$ES_z = \frac{x_{treatment} - x_{comparison}}{sd_x}$$

# Cohen's d

In contrast, Cohen's d is the difference between two groups divided by a *pooled* standard deviation, where the pooled standard deviation is a weighted composite of the two groups. Following equations given in the Stata Manual (`help esize`):

$$d = \frac{x_{treatment} - x_{comparison}}{sd_{pooled}}$$
and

$$sd_{pooled} = \sqrt{\frac{(n_1-1)s_1^2 +(n_2-1)s_2^2}{n_1 +n_2 - 2}} $$

# Converting from $ES_z$ to Cohen's d

Based upon the above formulas, converting between the two effect sizes should be simple:

$$ES_z \left( \frac{sd_x}{sd_{pooled}} \right) = d$$
$sd_x$ is available from `summarize x`.

The standard deviation and number of observations for each group, where `group` is the grouping variable is available from `bysort group: summarize x`.

One can then calculate:

`display pooledsd = ((((n1-1)*(sd1^2)) + ((n2-1)*(sd2^2)))/(n1+n2-2))^.5`

and then perform the above calculation.



